# Generated by Django 3.2.5 on 2021-07-29 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inner_account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='phone_number',
        ),
    ]
