# Generated by Django 3.2.5 on 2021-08-01 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inner_account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cert',
            field=models.FileField(blank=True, null=True, upload_to='doctor_cert/%y/%m/%d'),
        ),
    ]
