# Generated by Django 3.2.4 on 2021-08-04 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inner_account', '0002_alter_customuser_cert'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
