# Generated by Django 3.2.4 on 2021-08-04 01:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('user_id', models.CharField(max_length=20)),
                ('date', models.DateTimeField()),
                ('hname', models.CharField(max_length=20)),
                ('dname', models.CharField(max_length=10)),
                ('dept', models.CharField(max_length=20)),
                ('body', models.TextField(max_length=300)),
                ('cert', models.ImageField(blank=True, null=True, upload_to='review/%y/%m/%d')),
                ('fun', models.ManyToManyField(blank=True, related_name='fun', to=settings.AUTH_USER_MODEL)),
                ('like', models.ManyToManyField(blank=True, related_name='like', to=settings.AUTH_USER_MODEL)),
                ('scrap', models.ManyToManyField(blank=True, related_name='scrap', to=settings.AUTH_USER_MODEL)),
                ('upset', models.ManyToManyField(blank=True, related_name='upset', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rcomment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=20)),
                ('comment_text', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rcomments', to='review.review')),
            ],
        ),
    ]
