# Generated by Django 3.2.4 on 2021-08-04 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
