# Generated by Django 3.2.5 on 2021-08-01 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='cert',
            field=models.ImageField(blank=True, null=True, upload_to='review/%y/%m/%d'),
        ),
    ]
