# Generated by Django 3.2.5 on 2021-08-03 04:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('review', '0002_review_fun'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='upset',
            field=models.ManyToManyField(blank=True, related_name='upset', to=settings.AUTH_USER_MODEL),
        ),
    ]
