# Generated by Django 3.2.5 on 2021-08-03 04:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('review', '0003_review_upset'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='scrap',
            field=models.ManyToManyField(blank=True, related_name='scrap', to=settings.AUTH_USER_MODEL),
        ),
    ]
