# Generated by Django 3.2.5 on 2021-08-13 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0007_alter_review_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='doc',
            field=models.BooleanField(default=False),
        ),
    ]
