# Generated by Django 3.2.5 on 2021-08-13 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('user_id', models.CharField(max_length=20)),
                ('date', models.DateTimeField()),
                ('dept', models.CharField(max_length=20)),
                ('body', models.TextField(max_length=300)),
                ('doc', models.CharField(max_length=20, null=True)),
                ('view_count', models.IntegerField(default=0)),
                ('fun', models.ManyToManyField(blank=True, related_name='qfun', to=settings.AUTH_USER_MODEL)),
                ('like', models.ManyToManyField(blank=True, related_name='qlike', to=settings.AUTH_USER_MODEL)),
                ('scrap', models.ManyToManyField(blank=True, related_name='qscrap', to=settings.AUTH_USER_MODEL)),
                ('upset', models.ManyToManyField(blank=True, related_name='qupset', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Qcomment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=20)),
                ('comment_text', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('doc', models.CharField(max_length=20, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qcomments', to='question.question')),
            ],
        ),
    ]
