# Generated by Django 3.2.5 on 2021-08-13 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0005_question_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='doc',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
