# Generated by Django 3.2.5 on 2021-07-31 07:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.CharField(choices=[('치과', '치과'), ('피부과', '피부과'), ('성형외과', '성형외과'), ('산부인과', '산부인과'), ('안과', '안과'), ('내과', '내과'), ('외과', '외과'), ('이비인후과', '이비인후과'), ('정형외과', '정형외과'), ('비뇨기과', '비뇨기과'), ('정신건강의학과', '정신건강의학과'), ('재활의학과', '재활의학과'), ('영상의학과', '영상의학과'), ('소아과', '소아과'), ('신경외과', '신경외과'), ('신경과', '신경과'), ('마취통층의학과', '마취통층의학과'), ('가정의학과', '가정의학과'), ('한의원', '한의원')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('user_id', models.CharField(max_length=50)),
                ('body', models.TextField(max_length=700)),
                ('date', models.DateTimeField()),
                ('view_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=20)),
                ('comment_text', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='question.question')),
            ],
        ),
    ]
