# Generated by Django 3.2.5 on 2021-08-04 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='scrap',
            new_name='scrap2',
        ),
    ]
