# Generated by Django 3.2.5 on 2021-08-04 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_rename_scrap_question_scrap2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='scrap2',
            new_name='scrap',
        ),
    ]
