# Generated by Django 3.2.5 on 2021-08-13 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_rename_scrap2_question_scrap'),
    ]

    operations = [
        migrations.AddField(
            model_name='qcomment',
            name='doc',
            field=models.BooleanField(default=False),
        ),
    ]
