# Generated by Django 3.2.5 on 2021-08-13 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_qcomment_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='doc',
            field=models.BooleanField(default=False),
        ),
    ]
