# Generated by Django 3.2.5 on 2021-08-04 03:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('review', '0002_review_view_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='fun',
            field=models.ManyToManyField(blank=True, related_name='rfun', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='rlike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='scrap',
            field=models.ManyToManyField(blank=True, related_name='rscrap', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='upset',
            field=models.ManyToManyField(blank=True, related_name='rupset', to=settings.AUTH_USER_MODEL),
        ),
    ]
