# Generated by Django 3.2.5 on 2021-08-11 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_auto_20210804_0312'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='check',
            field=models.BooleanField(default=False),
        ),
    ]
