# Generated by Django 3.2.4 on 2021-08-13 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_review_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='rcomment',
            name='doc',
            field=models.BooleanField(default=False),
        ),
    ]
