# Generated by Django 3.2.5 on 2021-08-13 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0009_alter_review_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rcomment',
            name='doc',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
