# Generated by Django 3.2.5 on 2021-08-13 20:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Icomment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=20)),
                ('comment_text', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('doc', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('user_id', models.CharField(max_length=20)),
                ('date', models.DateTimeField()),
                ('dept', models.CharField(max_length=20)),
                ('body', models.TextField(max_length=300)),
                ('doc', models.CharField(max_length=20, null=True)),
                ('view_count', models.IntegerField(default=0)),
            ],
        ),
    ]
