# Generated by Django 3.2.5 on 2021-08-13 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='fun',
            field=models.ManyToManyField(blank=True, related_name='ifun', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='information',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='ilike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='information',
            name='scrap',
            field=models.ManyToManyField(blank=True, related_name='iscrap', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='information',
            name='upset',
            field=models.ManyToManyField(blank=True, related_name='iupset', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='icomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='icomments', to='information.information'),
        ),
    ]
