# Generated by Django 3.2.5 on 2021-08-13 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0005_alter_information_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='doc',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
